src/objects/Contact.object
<CustomObject>
</CustomObject>

src/objects/Contact/fields/Available_Balance__c.field-meta.xml
<CustomField>
    <fullName>Available_Balance__c</fullName>
    <label>Available Balance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

src/objects/Contact/fields/Daily_Debit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Daily_Debit_Limit__c</fullName>
    <label>Daily Debit Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

src/objects/Contact/fields/Daily_Transaction_Limit_Count__c.field-meta.xml
<CustomField>
    <fullName>Daily_Transaction_Limit_Count__c</fullName>
    <label>Daily Transaction Limit Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Contact/fields/Monthly_Debit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Debit_Limit__c</fullName>
    <label>Monthly Debit Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

src/objects/Contact/fields/Monthly_Transaction_Limit_Count__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Transaction_Limit_Count__c</fullName>
    <label>Monthly Transaction Limit Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Contact/fields/Transaction_Limit__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Limit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transaction Limit</label>
    <referenceTo>Transaction_Limit__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Transaction_Enteries__c/Transaction_Enteries__c.object-meta.xml
<CustomObject>
    <label>Transaction Entry</label>
    <nameField>
        <label>Transaction Enteries Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transaction_Enteries__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transaction Entries</relationshipLabel>
    <relationshipName>Transaction_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Transaction_Enteries__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Transaction_Enteries__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Debit</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Transaction_Limit__c/Transaction_Limit__c.object-meta.xml
<CustomObject>
    <label>Transaction Limit</label>
    <nameField>
        <label>Transaction Limit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction Limits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction_Limit__c/fields/Maximum_Debit_Allowed_Per_Day__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Debit_Allowed_Per_Day__c</fullName>
    <label>Maximum Debit Allowed Per Day</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

src/objects/Transaction_Limit__c/fields/Maximum_Debit_Allowed_Per_Month__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Debit_Allowed_Per_Month__c</fullName>
    <label>Maximum Debit Allowed Per Month</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

src/objects/Transaction_Limit__c/fields/Maximum_Debit_Allowed_Per_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Debit_Allowed_Per_Transaction__c</fullName>
    <label>Maximum Debit Allowed Per Transaction</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

src/objects/Transaction_Limit__c/fields/Maximum_Transaction_Allowed_Per_Day__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Transaction_Allowed_Per_Day__c</fullName>
    <label>Maximum Transaction Allowed Per Day</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Transaction_Limit__c/fields/Maximum_Transaction_Allowed_Per_Mon__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Transaction_Allowed_Per_Mon__c</fullName>
    <label>Maximum Transaction Allowed Per Month</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/classes/SendMonthlyEmailSchduleTest.cls
@isTest
public class SendMonthlyEmailSchduleTest {
    
    @isTest
    private static void testData() {
        
        List<Transaction_Limit__c> listOfTnxLimit = new List<Transaction_Limit__c>();
        
        Transaction_Limit__c limitOfHDFCBank = new Transaction_Limit__c();
        limitOfHDFCBank.name = 'HDFC';
        limitOfHDFCBank.Maximum_Debit_Allowed_Per_Month__c = 90000;
        limitOfHDFCBank.Maximum_Transaction_Allowed_Per_Mon__c = 50;
        limitOfHDFCBank.Maximum_Debit_Allowed_Per_Day__c = 20000;
        limitOfHDFCBank.Maximum_Transaction_Allowed_Per_Day__c = 3;
        limitOfHDFCBank.Maximum_Debit_Allowed_per_Transaction__c = 10000;  
        listOfTnxLimit.add(limitOfHDFCBank);
        
        Transaction_Limit__c limitOfICICIBank = new Transaction_Limit__c();
        limitOfICICIBank.name = 'ICICI';
        limitOfICICIBank.Maximum_Debit_Allowed_per_Month__c = 9000;
        limitOfICICIBank.Maximum_Transaction_Allowed_Per_Mon__c = 50;
        limitOfICICIBank.Maximum_Debit_Allowed_per_Day__c = 10000;
        limitOfICICIBank.Maximum_Transaction_Allowed_Per_Day__c = 22;
        limitOfICICIBank.Maximum_Debit_Allowed_per_Transaction__c = 10000;      
        listOfTnxLimit.add(limitOfICICIBank);
        insert listOfTnxLimit;
        
        
        List<Contact> listOfContact = new List<Contact>();
        Contact conForHDFC = new Contact();
        conForHDFC.LastName = 'Smith';
        conForHDFC.status__c = 'Active';
        conForHDFC.Email = 'test@test.com';
        conForHDFC.Available_Balance__c = 0;
        conForHDFC.Daily_Debit_Limit__c = 0;
        conForHDFC.Daily_Transaction_Limit_Count__c = 0;
        conForHDFC.Monthly_Debit_Limit__c = 0;
        conForHDFC.Monthly_Transaction_Limit_Count__c = 0;
        conForHDFC.Transaction_Limit__c = listOfTnxLimit[0].Id;
        listOfContact.add(conForHDFC);            
        insert listOfContact;
        
        List<Contact> listOfConId = new List<Contact>([Select Id From Contact Where LastName = 'Smith']);
        
        List<Transaction_Enteries__c> listOfCreditEntry = new List<Transaction_Enteries__c>();
        Transaction_Enteries__c  creditEntry = new Transaction_Enteries__c();
        creditEntry.Amount__c = 30000;
        creditEntry.Type__c = 'Credit';
        creditEntry.status__c = 'Completed';
        creditEntry.contact__c = listOfConId[0].id;
        creditEntry.Transaction_Date__c = System.today();
        insert creditEntry;
        
        Transaction_Enteries__c creditEntry2 = new Transaction_Enteries__c();
        creditEntry2.Amount__c = 5000;
        creditEntry2.Type__c = 'Debit';
        creditEntry2.status__c = 'Completed';
        creditEntry2.contact__c = listOfConId[0].id;
        creditEntry2.Transaction_Date__c = System.today();
        try {
            insert creditEntry2;
        } catch(Exception ex) {}
        
        creditEntry = new Transaction_Enteries__c();
        creditEntry.Amount__c = 250;
        creditEntry.Type__c = 'Debit';
        creditEntry.status__c = 'Completed';
        creditEntry.contact__c = listOfConId[0].id;
        creditEntry.Transaction_Date__c = System.today();
        insert creditEntry;
        
        creditEntry = new Transaction_Enteries__c();
        creditEntry.Amount__c = 1000;
        creditEntry.Type__c = 'Debit';
        creditEntry.status__c = 'Completed';
        creditEntry.contact__c = listOfConId[0].id;
        creditEntry.Transaction_Date__c = System.today(); 
        try {
            insert creditEntry;
        }
        catch(Exception ex){
        }
        
        SendMonthlyEmailSchdule.execute(null);  
    }
}