src/objects/Contact.object
<CustomObject>
</CustomObject>

src/objects/Contact/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <displayFormat>AccNo-{00000}</displayFormat>
    <label>Account Number</label>
    <type>AutoNumber</type>
</CustomField>

src/objects/Contact/fields/Available_Balance__c.field-meta.xml
<CustomField>
    <fullName>Available_Balance__c</fullName>
    <label>Available Balance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

src/objects/Transaction_Enteries__c/Transaction_Enteries__c.object-meta.xml
<CustomObject>
    <label>Transaction Entry</label>
    <nameField>
        <label>Transaction Enteries Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transaction_Enteries__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transaction Entries</relationshipLabel>
    <relationshipName>Transaction_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Transaction_Enteries__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Transaction_Enteries__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Debit</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/SendMonthlyEmailSchdule.cls
global with sharing class SendMonthlyEmailSchdule implements Schedulable {
    global void execute(SchedulableContext sc) {
        List<Contact> conList = [Select Id, Name, Available_Balance__c, Account_Number__c, Status__c, Email FROM Contact];
        List<Transaction_Enteries__c> txnList = [Select Id, Amount__c, Type__c, Transaction_Date__c, Contact__c From Transaction_Enteries__c Where Contact__c In : conList];
        List<Messaging.Email> emailList = new List<Messaging.Email>();

        for(Contact con: conList){
            if(con.Status__c=='Active'){
                Messaging.SingleEmailMessage emailMsg = new Messaging.SingleEmailMessage();
                emailMsg.setToAddresses(new String[]{con.Email});
                emailMsg.setSubject(con.Name);
                String htmlBody = '';
                for(Transaction_Enteries__c txn :txnList){
                    if(con.Id==txn.Contact__c){
                        htmlBody='Greeting From Axis Bank<br> <table border="1" style="border-collapse: collapse"><tr><th>Account Number</th><th>Type</th><th>Amount</th><th>Transaction Date</th></tr>';
                        htmlBody += '<tr><td>' + con.Account_Number__c + '</td><td>' + txn.Type__c + '</td><td>' + txn.Amount__c + '</td><td>' + txn.Transaction_Date__c + '</td></tr>'; 
                        }
            emailMsg.setHtmlBody(htmlBody);
            }
            emailList.add(emailMsg);
            }
        }
        Messaging.sendEmail(emailList);
    }
}