src/objects/Contact.object
<CustomObject>
</CustomObject>

src/objects/Contact/fields/Available_Balance__c.field-meta.xml
<CustomField>
    <fullName>Available_Balance__c</fullName>
    <label>Available Balance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

src/objects/Contact/fields/Daily_Debit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Daily_Debit_Limit__c</fullName>
    <label>Daily Debit Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

src/objects/Contact/fields/Daily_Transaction_Limit_Count__c.field-meta.xml
<CustomField>
    <fullName>Daily_Transaction_Limit_Count__c</fullName>
    <label>Daily Transaction Limit Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Contact/fields/Monthly_Debit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Debit_Limit__c</fullName>
    <label>Monthly Debit Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

src/objects/Contact/fields/Monthly_Transaction_Limit_Count__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Transaction_Limit_Count__c</fullName>
    <label>Monthly Transaction Limit Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Contact/fields/Transaction_Limit__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Limit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transaction Limit</label>
    <referenceTo>Transaction_Limit__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Transaction_Enteries__c/Transaction_Enteries__c.object-meta.xml
<CustomObject>
    <label>Transaction Entry</label>
    <nameField>
        <label>Transaction Enteries Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transaction_Enteries__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transaction Entries</relationshipLabel>
    <relationshipName>Transaction_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Transaction_Enteries__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Transaction_Enteries__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Debit</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Transaction_Limit__c/Transaction_Limit__c.object-meta.xml
<CustomObject>
    <label>Transaction Limit</label>
    <nameField>
        <label>Transaction Limit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction Limits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction_Limit__c/fields/Maximum_Debit_Allowed_Per_Day__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Debit_Allowed_Per_Day__c</fullName>
    <label>Maximum Debit Allowed Per Day</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

src/objects/Transaction_Limit__c/fields/Maximum_Debit_Allowed_Per_Month__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Debit_Allowed_Per_Month__c</fullName>
    <label>Maximum Debit Allowed Per Month</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

src/objects/Transaction_Limit__c/fields/Maximum_Debit_Allowed_Per_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Debit_Allowed_Per_Transaction__c</fullName>
    <label>Maximum Debit Allowed Per Transaction</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

src/objects/Transaction_Limit__c/fields/Maximum_Transaction_Allowed_Per_Day__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Transaction_Allowed_Per_Day__c</fullName>
    <label>Maximum Transaction Allowed Per Day</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Transaction_Limit__c/fields/Maximum_Transaction_Allowed_Per_Mon__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Transaction_Allowed_Per_Mon__c</fullName>
    <label>Maximum Transaction Allowed Per Month</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/classes/TransactionTriggerHelper.cls
public with sharing class TransactionTriggerHelper{
    
    public static void maintainDebitLimits(List<Transaction_Enteries__c> newTnxEntryList, Map<Id, Transaction_Enteries__c> mapOfOldTnxEntry){
        if(!newTnxEntryList.isEmpty())
        { 
            Set<Id> setOfContactId = new Set<Id>();
            for(Transaction_Enteries__c tnxEntryOfConId : newTnxEntryList)
            {   
                if(mapOfOldTnxEntry == null && tnxEntryOfConId.Type__c.equals('Debit'))
                    setOfContactId.add(tnxEntryOfConId.Contact__c);
            }
            
            Map<Id,Contact> mapOfContact = new Map<Id, Contact>([SELECT Id, Name, Status__c, Available_Balance__c, Monthly_Transaction_Limit_Count__c,
                                                                 Daily_Transaction_Limit_Count__c,
                                                                 Daily_Debit_Limit__c,
                                                                 Monthly_Debit_Limit__c,
                                                                 Transaction_Limit__r.Maximum_Debit_Allowed_Per_Day__c,
                                                                 Transaction_Limit__r.Maximum_Debit_Allowed_Per_Month__c,
                                                                 Transaction_Limit__r.Maximum_Debit_Allowed_Per_Transaction__c,
                                                                 Transaction_Limit__r.Maximum_Transaction_Allowed_Per_Day__c,
                                                                 Transaction_Limit__r.Maximum_Transaction_Allowed_Per_Mon__c
                                                                 FROM Contact WHERE Id IN : setOfContactId]);
            for(Transaction_Enteries__c tnxEntryOfConId : newTnxEntryList)
            {   
                if(mapOfOldTnxEntry == null && tnxEntryOfConId.Type__c.equals('Debit') && setOfContactId.contains(tnxEntryOfConId.contact__c))
                {   
                   
                    if(mapOfContact.get(tnxEntryOfConId.contact__c).Monthly_Transaction_Limit_Count__c > mapOfContact.get(tnxEntryOfConId.Contact__c).Transaction_Limit__r.Maximum_Transaction_Allowed_Per_Mon__c)
                    {
                       tnxEntryOfConId.addError('Monthly Transiction Limit Reached');   								
                    }
                    else if(mapOfContact.get(tnxEntryOfConId.contact__c).Daily_Transaction_Limit_Count__c > mapOfContact.get(tnxEntryOfConId.Contact__c).Transaction_Limit__r.Maximum_Transaction_Allowed_Per_Day__c)
                    {
                        tnxEntryOfConId.addError('Daily Transiction Limit Reached');   								
                    }
                    else if(mapOfContact.get(tnxEntryOfConId.contact__c).Monthly_Debit_Limit__c + tnxEntryOfConId.Amount__c > mapOfContact.get(tnxEntryOfConId.Contact__c).Transaction_Limit__r.Maximum_Debit_Allowed_Per_Month__c)
                    {
                       tnxEntryOfConId.addError('Monthly Debit Limit Reached');   								
                    }
                    else if(mapOfContact.get(tnxEntryOfConId.contact__c).Daily_Debit_Limit__c + tnxEntryOfConId.Amount__c> mapOfContact.get(tnxEntryOfConId.Contact__c).Transaction_Limit__r.Maximum_Debit_Allowed_Per_Day__c)
                    {
                        tnxEntryOfConId.addError('Daily Debit Limit Reached');   								
                    }
                    else if(tnxEntryOfConId.Amount__c > mapOfContact.get(tnxEntryOfConId.Contact__c).Transaction_Limit__r.Maximum_Debit_Allowed_Per_Transaction__c)
                    {
                        tnxEntryOfConId.addError('Maximum Debit Transiction Limit Reached');   								
                    }
                    
                }
            }
        }
    }
    
    public static void sumOFAvailableBalance(List<Transaction_Enteries__c> newTnxEntryList, Map<Id, Transaction_Enteries__c> mapOfOldTnxEntry){
        if(!newTnxEntryList.isEmpty())
        { 
            Set<Id> setOfContactId = new Set<Id>();
            for(Transaction_Enteries__c tnxEntryOfConId : newTnxEntryList)
            {   
                if(mapOfOldTnxEntry == null || mapOfOldTnxEntry != null && mapOfOldTnxEntry.get(tnxEntryOfConId.Id).status__c != tnxEntryOfConId.Status__c)
                    setOfContactId.add(tnxEntryOfConId.Contact__c);
            }
            System.debug('++++====>>>>'+setOfContactId); 
            
            
            Map<Id,Contact> mapOfContact = new Map<Id, Contact>([SELECT Id, Name, Status__c, Available_Balance__c FROM Contact WHERE Id IN : setOfContactId]);
            //List of contact To be update
            Map<Id, Contact> MapOfContactToBeUpdate = new Map<Id, Contact>();
            
            for(Transaction_Enteries__c tnxEntry :newTnxEntryList)
            {
                if(mapOfContact.get(tnxEntry.Contact__c).Status__c == 'Active' && setOfContactId.contains(tnxEntry.Contact__c))
                {   
                    if(!MapOfContactToBeUpdate.containsKey(tnxEntry.Contact__c))
                    {
                        Contact objContact = new Contact();
                        if(tnxEntry.Type__c.equals('Debit') && tnxEntry.Status__c.equals('Completed'))
                        {
                            objContact.Id = tnxEntry.Contact__c;
                            objContact.Available_Balance__c = mapOfContact.get(tnxEntry.Contact__c).Available_Balance__c - tnxEntry.Amount__c;
                            MapOfContactToBeUpdate.put(objContact.Id, objContact);
                            
                            for(AggregateResult agMonth : [SELECT COUNT(Id) NumberOfTransactionInMonth, SUM(Amount__c) totalDebitInMonth, Contact__c FROM 
                                                           Transaction_Enteries__c Where Type__c = 'Debit' AND 
                                                           Transaction_Date__c = THIS_MONTH GROUP BY Contact__c])
                            {   
                                objContact.Id = (Id)agMonth.get('Contact__c');
                                objContact.Monthly_Debit_Limit__c = (Decimal)agMonth.get('totalDebitInMonth');
                                objContact.Monthly_Transaction_Limit_Count__c = (Decimal)agMonth.get('NumberOfTransactionInMonth');
                            }
                            
                            for(AggregateResult agDay : [SELECT COUNT(Id) NumberOfTransactionInDay, SUM(Amount__c) totalDebitInDay, Contact__c FROM Transaction_Enteries__c Where Type__c = 'Debit' AND Transaction_Date__c = TODAY GROUP BY Contact__c])
                            {
                                objContact.Id = (Id)agDay.get('Contact__c');
                                objContact.Daily_Debit_Limit__c = (Decimal)agDay.get('totalDebitInDay');
                                objContact.Daily_Transaction_Limit_Count__c = (Decimal)agDay.get('NumberOfTransactionInDay');
                            }
                            
                        }
                        else if(tnxEntry.Type__c.equals('Credit') && tnxEntry.Status__c.equals('Completed'))
                        {
                            objContact.Id = tnxEntry.Contact__c;
                            objContact.Available_Balance__c = mapOfContact.get(tnxEntry.Contact__c).Available_Balance__c + tnxEntry.Amount__c;
                            MapOfContactToBeUpdate.put(objContact.Id, objContact);
                        }
                        else if(tnxEntry.Type__c.equals('Debit') && tnxEntry.Status__c.equals('Cancelled'))
                        {
                            objContact.Id = tnxEntry.Contact__c;
                            objContact.Available_Balance__c = mapOfContact.get(tnxEntry.Contact__c).Available_Balance__c + tnxEntry.Amount__c;
                            MapOfContactToBeUpdate.put(objContact.Id, objContact);
                        }
                        else if(tnxEntry.Type__c.equals('Credit') && tnxEntry.Status__c.equals('Cancelled'))
                        {
                            objContact.Id = tnxEntry.Contact__c;
                            objContact.Available_Balance__c = mapOfContact.get(tnxEntry.Contact__c).Available_Balance__c - tnxEntry.Amount__c;
                            MapOfContactToBeUpdate.put(objContact.Id, objContact);
                        }
                    }
                }
            }
            System.debug('+++++++====>>>'+MapOfContactToBeUpdate);
            
            if(MapOfContactToBeUpdate.size() > 0)
            {
                update MapOfContactToBeUpdate.values();
            }
        }
    }
}