src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Father_Mobile_Number__c</fullName>
        <label>Father Mobile Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Father_Name__c</fullName>
        <label>Father Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HomePhone__c</fullName>
        <label>HomePhone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Mobile_Number__c</fullName>
        <label>Mobile Number</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Overall_Grade__c</fullName>
        <label>Overall Grade</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Roll_Number__c</fullName>
        <label>Roll Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/StudentManager.cls
public class StudentManager {
    
    public static void insertStudent(){
    Student__c s1 = new Student__c();
     
    //insert student persnol info
    //
        s1.Name = 'Shivam Sahu';
        s1.Roll_Number__c = 46823;
        s1.Father_Name__c = 'Hukum Singh';
        s1.Mobile_Number__c = 91-941-754-8624;
        s1.Father_Mobile_Number__c = '91-953-041-5758';
        s1.HomePhone__c = '91-056-412-4589';
        s1.Email__c = 'Shivam.sahu@gmail.com';
        s1.Address__c = 'Purani mandi, Alwar';
        s1.Overall_Grade__c = 75;
        insert s1;
        
        
      // get inserted record id
        system.debug(s1.Id);
      
    }
}