src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Roll_Number__c</fullName>
        <label>Roll Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/QueryStudent.cls
Public class QueryStudent{

    public QueryStudent(){
        //Query Single Student Record 
        
        Student__c student = [select id, Name, Roll_Number__c from Student__c order by createdDate DESC LIMIT 1];
        system.debug(student);
		/* Query 5 Students
		  
		  
		List<Student__c> studentList = [select id, Name, Roll_Number__c from Student__c order by createdDate DESC LIMIT 5];
		for(Student__c stu : studentList){
			system.debug('Check Student Data ::: ' + stu);
		}


       */
	}
}