src/objects/Transaction_Enteries__c/Transaction_Enteries__c.object-meta.xml
<CustomObject>
    <label>Transaction Entry</label>
    <nameField>
        <label>Transaction Enteries Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transaction_Enteries__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transaction Entries</relationshipLabel>
    <relationshipName>Transaction_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Transaction_Enteries__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Transaction_Enteries__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Debit</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/TransactionListViewLwcController.cls
public class TransactionListViewLwcController {
      

    @AuraEnabled(cacheable=true)
    public static List<Transaction_Enteries__c> getTransactionEntries(Id conId, Integer selectedRecordLimits){
        return [SELECT Id, Name, Type__c, Status__c, Amount__c From Transaction_Enteries__c WHERE Contact__c =: conId AND Status__c != 'Cancelled' LIMIT : selectedRecordLimits];
    }

    @AuraEnabled(cacheable=true)
    public static List<Transaction_Enteries__c> getTransactionDataToExport(Id conId, Date startDate, Date endDate){
        List<Transaction_Enteries__c> transactionsRecord = [SELECT Id, Name, Type__c, Amount__c, Status__c, Transaction_Date__c FROM Transaction_Enteries__c where Contact__c =: conId AND
                                                            Transaction_Date__c >=: startDate AND Transaction_Date__c <=: endDate];
        return transactionsRecord;
    }
}