src/objects/Transaction_Enteries__c/Transaction_Enteries__c.object-meta.xml
<CustomObject>
    <label>Transaction Entry</label>
    <nameField>
        <label>Transaction Enteries Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transaction_Enteries__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transaction Entries</relationshipLabel>
    <relationshipName>Transaction_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Transaction_Enteries__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Transaction_Enteries__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Debit</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/ContactTriggerHandlerTest.cls
@isTest
public class ContactTriggerHandlerTest {
    
    @isTest
    public static void contactCantBeDeleteTest(){
        List<Contact> listCon = new List<Contact>();
        Contact con = new Contact(FirstName = 'Test', LastName = '1245');
        listCon.add(con);
        insert listCon;
        
        Transaction_Enteries__c tra = new Transaction_Enteries__c();
        tra.contact__c = con.Id;
        tra.Name = 'Test Transaction';
        tra.Type__c = 'Debit';
        tra.Amount__c = 2000;
        tra.status__c = 'Completed';
        tra.Transaction_Date__c = date.parse('10/17/2022');
        
        ContactTriggerHandler.contactCanNotBeDelete(listCon);
        
    }
}